// workspaces/client/mitosis/svelte/src/Components/MasherApp/MasherAppFunction.svelte
<script>
  import { getContext } from "svelte";

  import ClientContext from "../../Contexts/ClientContext.context.js";

  export let message;

  let clientContext = getContext(ClientContext.key);

  let name = "Foo";
</script>

<div class="my-class-name">
  {message || "Hello"}
  {name}! !
  <slot />
</div>

// workspaces/client/mitosis/react/src/Components/MasherApp/MasherAppFunction.jsx
import * as React from "react";
import { useState, useContext } from "react";
import ClientContext from "../../Contexts/ClientContext.context.js";

function MasherApp(props) {
  const [name, setName] = useState(() => "Foo");

  const clientContext = useContext(ClientContext);

  return (
    <div className="my-class-name">
      {props.message || "Hello"}
      {name}! !{props.children}
    </div>
  );
}

export default MasherApp;
